#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

pushd ${SCRIPT_DIR}

cp include/argshelper /usr/local/include/

# packages
debconf-set-selections <<EOF
debconf debconf/frontend select Noninteractive
EOF
apt-get install -y jq debian-keyring debian-archive-keyring apt-transport-https curl ed rsyslog

# user
id -u ops || adduser --home /home/ops --shell /bin/bash --disabled-password --gecos "Ops Team" ops

# conf
cp conf/sudoers /etc/sudoers.d/91-ops
cp conf/sshd_ca.conf /etc/ssh/sshd_config.d/

mkdir -p /home/ubuntu/init/creds/
mkdir -p /home/ubuntu/init/certs/
chown -R ubuntu /home/ubuntu/init

# scripts
cp scripts/* /usr/local/bin/

# trust init/certs/
gettlsca

# vault CA
if [[ -f /home/ubuntu/init/creds/ssh_host_role_id && -f /home/ubuntu/init/creds/vault.env ]]
then
	source /home/ubuntu/init/creds/vault.env
	sudo /usr/local/bin/getsshcert --vault ${VAULT_ADDR} --roleid /home/ubuntu/init/creds/ssh_host_role_id
	sudo /usr/local/bin/getsshclientca --vault ${VAULT_ADDR}

	cat << EOC | sudoappend /etc/ssh/sshd_config.d/ca.conf
TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem
HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub
EOC

	sudo systemctl restart sshd
fi

# alloy log export
mkdir -p /etc/apt/keyrings/
wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list

# apt.grafana.com unexpected package size errors
if ! apt-get update
then
	wget https://github.com/grafana/alloy/releases/download/v1.1.0/alloy-1.1.0-1.amd64.deb
	dpkg -i alloy-1.1.0-1.amd64.deb
else
	apt-get install alloy
fi

mkdir -p /etc/alloy
cp conf/config.alloy /etc/alloy/config.alloy

if [[ -f /home/ubuntu/init/creds/alloy.passwd ]]
then
	enablealloy.sh
fi

popd