#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: s3-credentials
stringData:
  S3_LOKI_ACCESS_KEY_ID: #@ data.values.accessKeyId
  S3_LOKI_SECRET_ACCESS_KEY: #@ data.values.secretKey