#!/usr/bin/env bash
set -euo pipefail
source /usr/local/include/ldapauthhelper

USER_UID=$1
CN=$2
OU=Systems

cat << EOF > /tmp/${USER_UID}.ldif
dn: uid=${USER_UID},ou=${OU},${SUFFIX}
objectClass: inetOrgPerson
uid: ${USER_UID}
sn: ${USER_UID}
givenName: ${USER_UID}
cn: $CN
displayName: $CN
mail: ${USER_UID}@${DOMAIN}
EOF

ldapadd -H ldaps://${HOST} -f /tmp/${USER_UID}.ldif $AUTH_ARGS