#!/usr/bin/env bash
set -euo pipefail
source /usr/local/include/ldapauthhelper

USER_UID=$1
GIVEN_NAME=$2
SURNAME=$3
EMAIL=$4
OU=${5:-People}

cat << EOF > /tmp/${USER_UID}.ldif
dn: uid=${USER_UID},ou=${OU},${SUFFIX}
objectClass: inetOrgPerson
uid: ${USER_UID}
sn: $SURNAME
givenName: $GIVEN_NAME
cn: $GIVEN_NAME
displayName: $GIVEN_NAME $SURNAME
mail: $EMAIL
EOF

ldapadd -H ldaps://${HOST} -f /tmp/${USER_UID}.ldif $AUTH_ARGS