#!/usr/bin/env bash
set -euo pipefail
source /usr/local/include/ldapauthhelper

CN=$1

cat << EOF > /tmp/${CN}.ldif
dn: cn=${CN},ou=Groups,${SUFFIX}
objectClass: groupOfNames
cn: ${CN}
member: uid=dummy,${SUFFIX}
EOF

ldapadd -H ldaps://${HOST} -f /tmp/${CN}.ldif $AUTH_ARGS