#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

pushd ${SCRIPT_DIR}

# args
OPTIONS=(user domain ldap)

help_this="change user's ldap password"
help_domain="parent domain of this environment"
help_ldap="ldap directory url"
help_user="user to modify (default current user)"

source /usr/local/include/argshelper
parseargs $@
requireargs domain ldap

if [[ -z "$user" ]]
then
	user=$(whoami)
fi

# ldap dc components from $domain
export suffix=$(sed -e 's/\./ /g' <<< ${domain} | xargs printf ",dc=%s" | sed -e 's/^,//')

ldappasswd -x -D uid=${user},ou=people,${suffix} -W -S uid=${user},ou=people,${suffix} -H ${ldap}