#!/usr/bin/env bash
set -euo pipefail

PLACEHOLDER_CRED=$((tr -dc A-Za-z0-9 </dev/urandom || [[ $(kill -L $?) == PIPE ]]) | head -c 16)
ACME=https://step.home.arpa/acme/acme/directory
ZONE=home.arpa
SUFFIX='dc=home,dc=arpa'
IP=$(ip -4 -j address show eth0 | jq -r '.[0].addr_info[0].local')

wget --progress=dot:giga https://dl.smallstep.com/gh-release/cli/docs-cli-install/v0.25.1/step-cli_0.25.1_amd64.deb
wget --progress=dot:giga https://dl.smallstep.com/gh-release/certificates/gh-release-header/v0.25.2/step-ca_0.25.2_amd64.deb
dpkg -i step-cli_0.25.1_amd64.deb
dpkg -i step-ca_0.25.2_amd64.deb
setcap CAP_NET_BIND_SERVICE=+eip $(which step-ca)

mkdir /etc/step-ca
echo $PLACEHOLDER_CRED > /etc/step-ca/password.txt
chmod 400 /etc/step-ca/password.txt

export STEPPATH=/etc/step-ca
step ca init --remote-management --acme \
  --name homelab-pki \
  --dns step.${ZONE} \
  --address ${IP}:443 \
  --with-ca-url https://step.${ZONE} \
  --provisioner cert-provisioner \
  --password-file /etc/step-ca/password.txt

mv /run/ca.json /etc/step-ca/config/ca.json
chown -R step:step /etc/step-ca

cp -r /etc/step-ca/certs/* /usr/local/share/ca-certificates/
chmod -R a+r /usr/local/share/ca-certificates/*.crt
update-ca-certificates

wget --progress=dot:giga https://raw.githubusercontent.com/smallstep/certificates/v0.25.2/systemd/step-ca.service -O /etc/systemd/system/step-ca.service

#systemctl daemon-reload
systemctl enable --now step-ca

while ! curl -fSsL https://step.${ZONE}:443/health; do echo waiting for step ca; sleep 2; done

sudo -u ubuntu -- bash -c "export STEPPATH=/home/ubuntu/.step; step ca bootstrap --ca-url https://step.${ZONE}:443 --install --fingerprint $(step certificate fingerprint  /usr/local/share/ca-certificates/root_ca.crt)"

curl -fSsL 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -fSsL 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
apt-get update
apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes caddy
step certificate fingerprint /etc/step-ca/certs/root_ca.crt > /usr/share/caddy/fingerprint
cp /etc/step-ca/certs/root_ca.crt /usr/share/caddy/step_root_ca.crt
cp /etc/step-ca/certs/intermediate_ca.crt /usr/share/caddy/step_intermediate_ca.crt
rm /usr/share/caddy/index.html
usermod -aG step caddy
chmod g+rx /etc/step-ca/certs
chmod g+r /etc/step-ca/certs/root_ca.crt
chmod a+r /usr/share/caddy/*
systemctl restart caddy