#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

source ${SCRIPT_DIR}/api/auth

OPTIONS=(host name)

help_this="print the ID of the VM with the given name
  warning: name isn't required to be unique"
help_host="api hostname or ip"
help_name="name of vm to find"

source ${SCRIPT_DIR}/../cloudinit/base/include/argshelper

parseargs $@
requireargs host name

for node in $(curl -fsL -H"${auth}" https://${host}:8006/api2/json/nodes | jq -r .data[].node)
do
  vmid=$(curl -fsL -H"${auth}" https://${host}:8006/api2/json/nodes/${node}/qemu | jq -r ".data[] | select(.name == \"${name}\") | .vmid")
  if [[ -n "$vmid" ]]
  then
    echo $vmid
    exit 0
  fi
done

>&2 echo vm $name not found
exit 1
