#!/usr/bin/env bash
set -uo pipefail

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

source ${SCRIPT_DIR}/api/auth


OPTIONS=(host)

help_this="print the hostname and IP address of all VMs"
help_host="api hostname or ip"

source ${SCRIPT_DIR}/../cloudinit/base/include/argshelper

parseargs $@
requireargs host

for node in $(curl -fsL -H"${auth}" https://${host}:8006/api2/json/nodes | jq -r .data[].node)
do
  for vm in $(curl -fsL -H"${auth}" https://${host}:8006/api2/json/nodes/${node}/qemu | jq -r .data[].vmid)
  do
    config=$(curl -fsL -H"${auth}" https://${host}:8006/api2/json/nodes/${node}/qemu/${vm}/config | jq -r .data)
    if [[ "$(jq -r .template <<< $config)" == "1" ]]
    then
      continue
    fi
    ipconfig=$(jq -r .ipconfig0 <<< $config)
    name=$(jq -r .name <<< $config)
    ip=$(sed -nr 's:.*ip=(.*)/.*:\1:p' <<< $ipconfig)
    if [[ -z "${ip}" ]]
    then
      continue
    fi
    echo $name $ip
  done
done
