#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

FLAGS=(skip_domain)
OPTIONS=(vmname nameserver domain)

help_this="create a new vm with automatic ip and dns. passthrough args to newvm"
help_skip_domain="do not add DNS records for this host"
help_vmname="unique name for the new VM"
help_nameserver="authorative name server to register the host with"
help_domain="parent domain of this environment"

source ${SCRIPT_DIR}/../cloudinit/base/include/argshelper

parseargs "$@"
requireargs vmname nameserver


echo set up ${vmname}
export ip=$(${SCRIPT_DIR}/ips --next)

if [[ "${skip_domain:-}" != "1" ]]
then
  ssh ubuntu@${nameserver} addhost.sh ${vmname} $ip
fi

${SCRIPT_DIR}/newvm --vmname ${vmname} --ip $ip ${PASSTHROUGH[@]}

if [[ "${skip_domain:-}" != "1" ]]
then
  ${SCRIPT_DIR}/waitforhost ${vmname}.${domain}
fi