#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

FLAGS=(skip_domain)
OPTIONS=(vmname userdata)

help_this="create a new vm with automatic ip and dns. passthrough args to newvm"
help_skip_domain="do not add DNS records for this host"
help_vmname="unique name for the new VM"
help_userdata="filename of the cloudinit user data configuration in the proxmox snippets directory"

source ${SCRIPT_DIR}/../cloudinit/argshelper

parseargs "$@"
requireargs vmname

userdata=${userdata-$vmname}

echo set up ${vmname}
export ip=$(./workspace/proxmox/ips next)

if [[ "${skip_domain:-}" != "1" ]]
then
  ssh ubuntu@bind.home.arpa addhost.sh ${vmname} $ip
fi

if [[ -n "${userdata}" ]]
then
  ./workspace/cloudinit/${userdata}/generate.sh $ip
  ./workspace/proxmox/newvm --vmname ${vmname} --userdata ${userdata}.yml ${PASSTHROUGH[@]}
else
  ./workspace/proxmox/newvm --vmname ${vmname} ${PASSTHROUGH[@]}
fi

if [[ "${skip_domain:-}" != "1" ]]
then
  ./workspace/proxmox/waitforhost ${vmname}.home.arpa
fi