#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: loki
stringData:
  username: alloy
  password: #@ data.values.loki_password
  host: https://loki.eng.home.arpa
  