cluster:
  name: ${cluster}
metrics:
  enabled: true
  cost:
    enabled: false
opencost:
  enabled: false
externalServices:
  loki:
    secret:
      name: loki
      namespace: monitoring
      create: false
    host: https://loki.eng.home.arpa
    tls:
      ca_file: /etc/ssl/certs/root-certs.pem
  prometheus:
    secret:
      name: mimir
      namespace: monitoring
      create: false
    host: https://mimir.eng.home.arpa
    queryEndpoint: /prometheus/api/v1/query
    writeEndpoint: /api/v1/push
    tls:
      ca_file: /etc/ssl/certs/root-certs.pem
alloy:
  alloy:
    mounts:
      extra:
        - name: kubernetes-monitoring-telemetry
          mountPath: /etc/kubernetes-monitoring-telemetry
        - name: ca-bundle
          mountPath: /etc/ssl/certs
  controller:
    volumes:
      extra:
        - name: kubernetes-monitoring-telemetry
          configMap:
            name: kubernetes-monitoring-telemetry
        - name: ca-bundle
          configMap:
            name: ca-bundle
alloy-logs:
  alloy:
    mounts:
      extra:
        - name: kubernetes-monitoring-telemetry
          mountPath: /etc/kubernetes-monitoring-telemetry
        - name: ca-bundle
          mountPath: /etc/ssl/certs
  controller:
    volumes:
      extra:
        - name: kubernetes-monitoring-telemetry
          configMap:
            name: kubernetes-monitoring-telemetry
        - name: ca-bundle
          configMap:
            name: ca-bundle
alloy-events:
  alloy:
    mounts:
      extra:
        - name: kubernetes-monitoring-telemetry
          mountPath: /etc/kubernetes-monitoring-telemetry
        - name: ca-bundle
          mountPath: /etc/ssl/certs
  controller:
    volumes:
      extra:
        - name: kubernetes-monitoring-telemetry
          configMap:
            name: kubernetes-monitoring-telemetry
        - name: ca-bundle
          configMap:
            name: ca-bundle