#!/usr/bin/env bash
set -euo pipefail

PLACEHOLDER_ADMIN_CRED=$1
export ZONE=home.arpa

function generatecred {
  (tr -dc A-Za-z0-9 </dev/urandom || [[ $(kill -L $?) == PIPE ]]) | head -c 16
}
export -f generatecred

DB_CRED=$(generatecred)

wget --progress=dot:giga https://github.com/keycloak/keycloak/releases/download/22.0.0/keycloak-22.0.0.tar.gz
tar -xf keycloak-22.0.0.tar.gz
addgroup keycloak
adduser --system keycloak
adduser keycloak keycloak
mv keycloak-22.0.0 /opt/keycloak
rm keycloak-22.0.0.tar.gz
sed "s/db-password=/db-password=${DB_CRED}/" /run/keycloak.conf > /opt/keycloak/conf/keycloak.conf
chown -R keycloak /opt/keycloak
wget --progress=dot:giga https://repo1.maven.org/maven2/io/quarkiverse/systemd/notify/quarkus-systemd-notify-deployment/1.0.1/quarkus-systemd-notify-deployment-1.0.1.jar -O /opt/keycloak/providers/quarkus-systemd-notify-deployment-1.0.1.jar
wget --progress=dot:giga https://repo1.maven.org/maven2/io/quarkiverse/systemd/notify/quarkus-systemd-notify/1.0.1/quarkus-systemd-notify-1.0.1.jar -O /opt/keycloak/providers/quarkus-systemd-notify-1.0.1.jar
systemctl start postgresql.service
sudo -u postgres createuser keycloak
sudo -u postgres createdb keycloak
sudo -u postgres psql -c "ALTER USER keycloak PASSWORD '$DB_CRED';"
/opt/keycloak/bin/kc.sh build --db=postgres

export CERT_GROUP=keycloak
export FULLCHAIN_PATH=/opt/keycloak/conf/server.crt.pem
export PRIVKEY_PATH=/opt/keycloak/conf/server.key.pem
initcertbot keycloak.${ZONE}

systemctl enable keycloak
systemctl start keycloak
systemctl is-active keycloak --wait

while ! curl -fSsL  https://keycloak.home.arpa:8443/health
do
	echo waiting for keycloak
	sleep 2
done

create-realm --username admin --password ${PLACEHOLDER_ADMIN_CRED} --authrealm master --realm infrastructure

sync-realm --username admin --password ${PLACEHOLDER_ADMIN_CRED} --authrealm master --realm infrastructure

while ! /opt/keycloak/bin/kcadm.sh get groups -r infrastructure | grep keycloak-realm-admin
do
	echo waiting for realm sync from ldap
	sleep 2
done

# group by name only returns first two results
GROUP_ID=$(/opt/keycloak/bin/kcadm.sh get groups -r infrastructure -q search=keycloak-realm-admin | jq -r .[0].id)
/opt/keycloak/bin/kcadm.sh add-roles -r infrastructure --gid $GROUP_ID --cclientid realm-management --rolename realm-admin
