#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

pushd ${SCRIPT_DIR}

# args

OPTIONS=(domain acme ldap network nameserver subdomain)

help_this="initialize mail server"
help_domain="parent domain of this environment"
help_acme="acme directory url to acquire TLS cert"
help_ldap="ldap directory url"
help_network="internal network cidr"
help_nameserver="IP address of DNS resolver"
help_subdomain="subdomain for this service (defaults to hostname)"

../base/runcmd

source /usr/local/include/argshelper
parseargs $@
requireargs domain acme ldap network nameserver

if [[ -z "${subdomain}" ]]
then
  export subdomain=$(hostname)
fi

# ldap dc components from $domain
export suffix=$(sed -e 's/\./ /g' <<< ${domain} | xargs printf ",dc=%s" | sed -e 's/^,//')

# conf
mkdir -p /etc/dovecot/conf.d
mkdir -p /etc/postfix
mkdir -p /etc/clamav
mkdir -p /etc/spamassassin
mkdir -p /etc/opendkim
mkdir -p /var/mail/vmail/sieve-before
mkdir -p /var/lib/spamassassin/.razor

cp conf/10-auth.conf /etc/dovecot/conf.d/10-auth.conf
sed -e "s/\${domain}/${domain}/g" conf/999-mail-stack-delivery.conf > /etc/dovecot/conf.d/999-mail-stack-delivery.conf
sed -e "s/\${domain}/${domain}/g" conf/aliases > /etc/aliases
sed -e "s/\${domain}/${domain}/g" conf/auth-ldap.conf.ext > /etc/dovecot/conf.d/auth-ldap.conf.ext
sed -e "s/\${domain}/${domain}/g" conf/canonical > /etc/postfix/canonical
cp conf/clamav-milter /etc/default/clamav-milter
cp conf/clamav-milter.conf /etc/clamav/clamav-milter.conf
cp conf/default.sieve /var/mail/vmail/sieve-before/default.sieve
sed -e "s|\${ldap}|${ldap}|g" -e "s/\${suffix}/${suffix}/g" conf/dovecot-ldap.conf.ext > /etc/dovecot/dovecot-ldap.conf.ext
cp conf/init.pre /etc/spamassassin/init.pre
sed -e "s/\${hostname}/${subdomain}/g" -e "s/\${domain}/${domain}/g" conf/KeyTable > /etc/opendkim/KeyTable
sed -e "s|\${ldap}|${ldap}|g" -e "s/\${suffix}/${suffix}/g" conf/ldap-accounts.cf > /etc/postfix/ldap-accounts.cf
sed -e "s|\${ldap}|${ldap}|g" -e "s/\${suffix}/${suffix}/g" conf/ldap-aliases.cf > /etc/postfix/ldap-aliases.cf
sed -e "s|\${ldap}|${ldap}|g" -e "s/\${suffix}/${suffix}/g" conf/ldap-senders.cf > /etc/postfix/ldap-senders.cf
cp conf/local.cf /etc/spamassassin/local.cf
sed -e "s/\${hostname}/${subdomain}/g" -e "s/\${domain}/${domain}/g" conf/mailname > /etc/mailname
sed -e "s/\${hostname}/${subdomain}/g" -e "s/\${domain}/${domain}/g"  -e "s|\${network}|${network}|g" conf/main.cf > /etc/postfix/main.cf
cp conf/master.cf /etc/postfix/master.cf
sed -e "s/\${nameserver}/${nameserver}/g" conf/opendkim.conf > /etc/opendkim.conf
cp conf/razor-agent.conf /var/lib/spamassassin/.razor/razor-agent.conf
sed -e "s/\${hostname}/${subdomain}/g" -e "s/\${domain}/${domain}/g" conf/SigningTable > /etc/opendkim/SigningTable
cp conf/spamass-milter /etc/default/spamass-milter
cp conf/spamassassin /etc/default/spamassassin
cp conf/TrustedHosts /etc/opendkim/TrustedHosts
sed -e "s/\${domain}/${domain}/g" conf/virtual > /etc/postfix/virtual
sed -e "s/\${domain}/${domain}/g" conf/virtual-mailbox-domains > /etc/postfix/virtual-mailbox-domains

# setup
initcertbot --acme $acme --group mail --san ${subdomain}.${domain} --fullchain /etc/ssl/certs/tls.crt --key /etc/ssl/private/tls.key

debconf-set-selections <<EOF
postfix postfix/mailname        string  ${subdomain}.${domain}
postfix postfix/main_mailer_type        select  Internet Site
EOF

DEBIAN_FRONTEND=noninteractive apt-get -y  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install \
  postfix postfix-ldap mariadb-server \
  dovecot-core dovecot-imapd dovecot-mysql dovecot-ldap dovecot-sieve dovecot-managesieved \
  swaks opendkim opendkim-tools \
  spamass-milter pyzor razor libmail-dkim-perl \
  clamav clamav-daemon clamdscan python3-pip

# generate postfix .db files
newaliases
postmap /etc/postfix/canonical
postmap /etc/postfix/virtual
postmap /etc/postfix/virtual-mailbox-domains
postmap /etc/postfix/ldap-aliases.cf
postmap /etc/postfix/ldap-accounts.cf
postmap /etc/postfix/ldap-senders.cf

service postfix restart


# dovecot setup
groupadd -g 5000 vmail
useradd -g vmail -u 5000 vmail -d /var/mail/vmail -m
chown -R vmail:vmail /var/mail/vmail

unlink /etc/dovecot/private/dovecot.key
unlink /etc/dovecot/private/dovecot.pem

ln -s /etc/ssl/private/tls.key /etc/dovecot/private/dovecot.key
ln -s /etc/ssl/certs/tls.crt /etc/dovecot/private/dovecot.pem

service dovecot restart


# dkim setup
opendkim-genkey -r -h sha256 -d ${subdomain}.${domain} -s mail --directory /etc/opendkim
ln -s /etc/opendkim/mail.private /etc/opendkim/mail
chmod 400 /etc/opendkim/mail.private

chown -R opendkim:opendkim /etc/opendkim

mkdir /var/spool/postfix/opendkim
chown opendkim:root /var/spool/postfix/opendkim
usermod -G opendkim postfix

service opendkim restart


# spamassassin setup
usermod -a -G debian-spamd spamass-milter
mkdir /var/spool/postfix/spamassassin/
chown debian-spamd:root /var/spool/postfix/spamassassin/

spamassassin --lint
sa-update
sa-compile

mkdir -p /var/lib/spamassassin/.spamassassin
mkdir -p /var/lib/spamassassin/.razor
mkdir -p /var/lib/spamassassin/.pyzor
chown -R debian-spamd:debian-spamd /var/lib/spamassassin

service spamassassin restart && service spamass-milter restart

# hash-sharing DB for spam messages
razor-admin -home=/var/lib/spamassassin/.razor -register
razor-admin -home=/var/lib/spamassassin/.razor -create
razor-admin -home=/var/lib/spamassassin/.razor -discover


# clamav setup
mkdir /var/spool/postfix/clamav
chown clamav:root /var/spool/postfix/clamav/

pip install cvdupdate
cvdupdate update
cp /root/.cvdupdate/database/* /var/lib/clamav
chown -R clamav:clamav /var/lib/clamav

service clamav-daemon restart
systemctl is-active clamav-daemon --wait

DEBIAN_FRONTEND=noninteractive apt-get -y  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install \
  clamav-freshclam clamav-milter arj bzip2 cabextract cpio file gzip lhasa lzop nomarch p7zip pax rar rpm unrar unzip zip

systemctl is-active clamav-milter --wait


# sieve setup
mkdir -p /var/mail/vmail/sieve-before
mkdir -p /var/mail/vmail/sieve-after
chown -R vmail:vmail /var/mail/vmail/sieve-before
chown -R vmail:vmail /var/mail/vmail/sieve-after

sievec /var/mail/vmail/sieve-before/default.sieve
chown vmail:vmail /var/mail/vmail/sieve-before/default.svbin

service postfix reload