#!/usr/bin/env bash
set -euo pipefail

export ZONE=home.arpa
SUFFIX='dc=home,dc=arpa'

export CERT_GROUP=mail
export FULLCHAIN_PATH=/etc/ssl/certs/tls.crt
export PRIVKEY_PATH=/etc/ssl/private/tls.key
initcertbot mail.${ZONE}

debconf-set-selections <<EOF
postfix postfix/mailname        string  mail.${ZONE}
postfix postfix/main_mailer_type        select  Internet Site
EOF

DEBIAN_FRONTEND=noninteractive apt-get -y  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install \
  postfix postfix-ldap mariadb-server \
  dovecot-core dovecot-imapd dovecot-mysql dovecot-ldap dovecot-sieve dovecot-managesieved \
  swaks opendkim opendkim-tools \
  spamass-milter pyzor razor libmail-dkim-perl \
  clamav clamav-daemon clamdscan python3-pip

# generate postfix .db files
newaliases
postmap /etc/postfix/canonical
postmap /etc/postfix/virtual
postmap /etc/postfix/virtual-mailbox-domains
postmap /etc/postfix/ldap-aliases.cf
postmap /etc/postfix/ldap-accounts.cf
postmap /etc/postfix/ldap-senders.cf

service postfix restart


# dovecot setup
groupadd -g 5000 vmail
useradd -g vmail -u 5000 vmail -d /var/mail/vmail -m
chown -R vmail:vmail /var/mail/vmail

unlink /etc/dovecot/private/dovecot.key
unlink /etc/dovecot/private/dovecot.pem

ln -s /etc/ssl/private/tls.key /etc/dovecot/private/dovecot.key
ln -s /etc/ssl/certs/tls.crt /etc/dovecot/private/dovecot.pem

service dovecot restart


# dkim setup
opendkim-genkey -r -h sha256 -d mail.${ZONE} -s mail --directory /etc/opendkim
ln -s /etc/opendkim/mail.private /etc/opendkim/mail
chmod 400 /etc/opendkim/mail.private

chown -R opendkim:opendkim /etc/opendkim

mkdir /var/spool/postfix/opendkim
chown opendkim:root /var/spool/postfix/opendkim
usermod -G opendkim postfix

service opendkim restart


# spamassassin setup
usermod -a -G debian-spamd spamass-milter
mkdir /var/spool/postfix/spamassassin/
chown debian-spamd:root /var/spool/postfix/spamassassin/

spamassassin --lint
sa-update
sa-compile

mkdir -p /var/lib/spamassassin/.spamassassin
mkdir -p /var/lib/spamassassin/.razor
mkdir -p /var/lib/spamassassin/.pyzor
chown -R debian-spamd:debian-spamd /var/lib/spamassassin

service spamassassin restart && service spamass-milter restart

# hash-sharing DB for spam messages
razor-admin -home=/var/lib/spamassassin/.razor -register
razor-admin -home=/var/lib/spamassassin/.razor -create
razor-admin -home=/var/lib/spamassassin/.razor -discover


# clamav setup
mkdir /var/spool/postfix/clamav
chown clamav:root /var/spool/postfix/clamav/

pip install cvdupdate
cvdupdate update
cp /root/.cvdupdate/database/* /var/lib/clamav
chown -R clamav:clamav /var/lib/clamav

service clamav-daemon restart
systemctl is-active clamav-daemon --wait

DEBIAN_FRONTEND=noninteractive apt-get -y  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install \
  clamav-freshclam clamav-milter arj bzip2 cabextract cpio file gzip lhasa lzop nomarch p7zip pax rar rpm unrar unzip zip

systemctl is-active clamav-milter --wait


# sieve setup
mkdir -p /var/mail/vmail/sieve-before
mkdir -p /var/mail/vmail/sieve-after
chown -R vmail:vmail /var/mail/vmail/sieve-before
chown -R vmail:vmail /var/mail/vmail/sieve-after

sievec /var/mail/vmail/sieve-before/default.sieve
chown vmail:vmail /var/mail/vmail/sieve-before/default.svbin

service postfix reload