#!/usr/bin/env bash
set -euo pipefail

export ZONE=home.arpa
SUFFIX='dc=home,dc=arpa'

export CERT_GROUP=mail
export FULLCHAIN_PATH=/etc/ssl/certs/tls.crt
export PRIVKEY_PATH=/etc/ssl/private/tls.key
initcertbot mail.${ZONE}

debconf-set-selections <<EOF
postfix postfix/mailname        string  mail.${ZONE}
postfix postfix/main_mailer_type        select  Internet Site
EOF

DEBIAN_FRONTEND=noninteractive apt-get -y  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install \
  postfix postfix-ldap mariadb-server \
  dovecot-core dovecot-imapd dovecot-mysql dovecot-ldap \
  swaks

# generate postfix .db files
newaliases
postmap /etc/postfix/canonical
postmap /etc/postfix/virtual
postmap /etc/postfix/virtual-mailbox-domains
postmap /etc/postfix/ldap-aliases.cf
postmap /etc/postfix/ldap-accounts.cf
postmap /etc/postfix/ldap-senders.cf

service postfix restart


# dovecot setup
groupadd -g 5000 vmail
useradd -g vmail -u 5000 vmail -d /var/mail/vmail -m
chown -R vmail:vmail /var/mail/vmail

unlink /etc/dovecot/private/dovecot.key
unlink /etc/dovecot/private/dovecot.pem

ln -s /etc/ssl/private/tls.key /etc/dovecot/private/dovecot.key
ln -s /etc/ssl/certs/tls.crt /etc/dovecot/private/dovecot.pem

service dovecot restart