#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitlab-initial-root-password
stringData:
  password: #@ data.values.root_password
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: psql-password
stringData:
  password: #@ data.values.db_password
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitlab-redis-secret
stringData:
  redis-password: #@ data.values.redis_secret
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitaly-token
stringData:
  token: #@ data.values.gitaly_token
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-keys
stringData:
  accesskey: #@ data.values.minio_access
  secretkey: #@ data.values.minio_secret