#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: admin
stringData:
  HARBOR_ADMIN_PASSWORD: #@ data.values.admin_password
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: encryption
stringData:
  secretKey: #@ data.values.secret_key
  tls.key: #@ data.values.private_key
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: login
stringData:
  REGISTRY_PASSWD: #@ data.values.registry_login.password
  REGISTRY_HTPASSWD: #@ data.values.registry_login.hash