apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: ${hostname}.${domain}
networking:
  podSubnet: "10.244.0.0/16"
apiServer:
  certSANs:
  - ${hostname}.${domain}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true