#!/usr/bin/env bash
set -euo pipefail

ZONE=home.arpa
SUFFIX='dc=home,dc=arpa'

USERNAME=$1

cat > /usr/local/include/ldap.env << EOF
   SUFFIX=${SUFFIX}
   HOST=ldap.${ZONE}
   DOMAIN=${ZONE}
EOF

debconf-set-selections <<EOF
nslcd nslcd/ldap-reqcert string demand
nslcd nslcd/ldap-uris string ldaps://ldap.${ZONE}/
nslcd nslcd/ldap-base string $SUFFIX
nslcd nslcd/ldap-cacertfile string /etc/ssl/certs/ca-certificates.crt
nslcd nslcd/ldap-auth-type string none

ldap-auth-config ldap-auth-config/ldapns/ldap_version string 3
ldap-auth-config ldap-auth-config/ldapns/base-dn string $SUFFIX
ldap-auth-config ldap-auth-config/ldapns/ldap-server string ldaps://ldap.${ZONE}
ldap-auth-config ldap-auth-config/move-to-debconf boolean true
ldap-auth-config ldap-auth-config/dbrootlogin boolean false
ldap-auth-config ldap-auth-config/dblogin boolean false

EOF

wget --progress=dot:giga https://github.com/carvel-dev/ytt/releases/download/v0.46.3/ytt-linux-amd64 -O /usr/local/bin/ytt
chmod a+rx /usr/local/bin/ytt

wget --progress=dot:giga https://github.com/carvel-dev/kapp/releases/download/v0.60.0/kapp-linux-amd64 -O /usr/local/bin/kapp
chmod a+rx /usr/local/bin/kapp

wget --progress=dot:giga https://dl.smallstep.com/gh-release/cli/docs-cli-install/v0.24.4/step-cli_0.24.4_amd64.deb
dpkg -i step-cli_0.24.4_amd64.deb
wget --progress=dot:giga -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

apt-get update
apt-get install -y lubuntu-desktop xrdp firefox ldap-utils libpam-ldap  libnss-ldap nslcd vault

service xrdp restart
sudo systemctl enable nslcd
systemctl start nslcd

wget --progress=dot:giga https://github.com/keycloak/keycloak/releases/download/22.0.0/keycloak-22.0.0.tar.gz
tar -xf keycloak-22.0.0.tar.gz
mv keycloak-22.0.0/bin/* /usr/local/bin/
rm keycloak-22.0.0.tar.gz

curl -fSsL -o /usr/local/share/ca-certificates/step_root_ca.crt https://step.${ZONE}:8443/step_root_ca.crt
curl -fSsL -o /usr/local/share/ca-certificates/step_intermediate_ca.crt https://step.${ZONE}:8443/step_intermediate_ca.crt

mkdir -p /etc/firefox/ca-certificates
chmod a+rx /etc/firefox/ca-certificates
cp /usr/local/share/ca-certificates/step_root_ca.crt /etc/firefox/ca-certificates/step_root_ca.crt
chmod a+r /etc/firefox/ca-certificates/step_root_ca.crt

wget --progress=dot:giga https://get.pinniped.dev/v0.28.0/pinniped-cli-linux-amd64
mv pinniped-cli-linux-amd64 /usr/local/bin/pinniped
chmod a+rx /usr/local/bin/pinniped

snap install helm --classic
snap install kubectl --classic
snap install yq

apt-get install -y docker.io docker-compose
usermod -aG docker $USERNAME

export USERNAME

wget --progress=dot:giga https://github.com/docker/docker-credential-helpers/releases/download/v0.8.1/docker-credential-secretservice-v0.8.1.linux-amd64 \
  -O /usr/local/bin/docker-credential-secretservice
chmod a+rx /usr/local/bin/docker-credential-secretservice

mkdir -p /home/${USERNAME}/.docker
cat > /home/${USERNAME}/.docker/config.json <<EOF
{
  "credsStore": "secretservice"
}
EOF
chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.docker

shutdown -r +1