#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: loki-datasource
  namespace: monitoring
  labels:
     grafana_datasource: "1"
type: Opaque
stringData:
  #@yaml/text-templated-strings
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: https://loki.eng.home.arpa
      basicAuth: true
      basicAuthUser: (@= data.values.grafana_user @)
      secureJsonData:
        basicAuthPassword: (@= data.values.grafana_password @)
    - name: Prometheus
      type: prometheus
      access: proxy
      url: https://mimir.eng.home.arpa/prometheus
      basicAuth: true
      basicAuthUser: (@= data.values.grafana_user @)
      secureJsonData:
        basicAuthPassword: (@= data.values.grafana_password @)