#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

OPTIONS=(length)

help_this="generate an alphanumeric password"
help_length="number of characters (default 32)"

if [[ -f /usr/local/include/argshelper ]]
then
  source /usr/local/include/argshelper
elif [[ -f ${SCRIPT_DIR}/../include/argshelper ]]
then
  source ${SCRIPT_DIR}/../include/argshelper
fi
parseargs $@

length=${length:-32}

(tr -dc A-Za-z0-9 </dev/urandom || [[ $(kill -L $?) == PIPE ]]) | head -c $length

# write newline to stderr in interactive shell
if [ -t 1 ]
then
  >&2 echo
fi