#!/usr/bin/env bash
set -euo pipefail

FLAGS=(certbot step)
OPTIONS=(acme san group fullchain chain cert key)

help_this="generate a certificate"
help_certbot="install certbot and acquire a certificate from the smallstep CA via http01 challenge (default)"
help_step="use step cli and admin credentials to generate a certificate"
help_acme="acme directory url"
help_san="desired SAN"
help_group="linux group to grant read access to generated certs and keys"
help_fullchain="desired location of a fullchain pem (containing cert and CA)"
help_chain="desired location of a chain pem (containing CA)"
help_cert="desired location of a certificate pem"
help_key="desired location of a private key pem"

source /usr/local/include/argshelper
parseargs $@
requireargs acme san group

if [[ "${certbot}" == "0" && "${step}" == "1" || -d /etc/step-ca ]]
then
  if [[ ! -d /root/.step ]]
  then
    bash -c "export STEPPATH=/root/.step; step ca bootstrap --ca-url ${acme} --install --fingerprint $(step certificate fingerprint  /usr/local/share/ca-certificates/root_ca.crt)"
  fi

  expiry=$(date -d "$(date +%Y-%m-%d) + 1 year" "+%Y-%m-%dT00:00:00Z")
  mkdir -p /etc/letsencrypt/live/${san}
  mkdir -p /etc/letsencrypt/archive
  ln -s /etc/letsencrypt/live/${san} /etc/letsencrypt/archive/${san}
  step ca certificate $san /etc/letsencrypt/live/${san}/cert.pem /etc/letsencrypt/live/${san}/privkey.pem \
    --provisioner cert-provisioner --not-after=${expiry} --password-file /etc/step-ca/password.txt

  cat /etc/step-ca/certs/root_ca.crt > /etc/letsencrypt/live/${san}/chain.pem
  cat  /etc/letsencrypt/live/${san}/cert.pem /etc/letsencrypt/live/${san}/chain.pem > /etc/letsencrypt/live/${san}/fullchain.pem

else

  if [[ ! -f /usr/bin/certbot ]]
  then
    snap install --classic certbot
    ln -s /snap/bin/certbot /usr/bin/certbot
  fi

  export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
  if ! grep -q REQUESTS_CA_BUNDLE /etc/environment
  then
    echo "REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt" | sudoappend /etc/environment
  fi

  certbot certonly --standalone --server ${acme}/acme/acme/directory --register-unsafely-without-email --cert-name ${san} -d ${san} || certbot renew

fi

chmod a+rx /etc/letsencrypt/archive
chmod g+rx /etc/letsencrypt/archive/${san}
chmod a+rx /etc/letsencrypt/live
chmod g+rx /etc/letsencrypt/live/${san}
if [[ -n "${fullchain:-}" ]]
then
  mkdir -p $(dirname $fullchain)
  rm -rf $fullchain
  ln -s /etc/letsencrypt/live/${san}/fullchain.pem $fullchain
  chmod 640 $fullchain
fi
if [[ -n "${chain:-}" ]]
then
  mkdir -p $(dirname $chain)
  rm -rf $chain
  ln -s /etc/letsencrypt/live/${san}/chain.pem $chain
  chmod 640 $chain
fi
if [[ -n "${cert:-}" ]]
then
  mkdir -p $(dirname $cert)
  rm -rf $cert
  ln -s /etc/letsencrypt/live/${san}/cert.pem $cert
  chmod 640 $cert
fi
if [[ -n "${key:-}" ]]
then
  mkdir -p $(dirname $key)
  rm -rf $key
  ln -s /etc/letsencrypt/live/${san}/privkey.pem $key
  chmod 640 $key
fi

chmod a+rx /etc/letsencrypt
chgrp -R $group /etc/letsencrypt/archive/${san}/