#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

pushd ${SCRIPT_DIR}

# args
OPTIONS=(domain acme userfile subdomain)

help_this="initialize ldap server"
help_domain="parent domain of this environment"
help_acme="acme directory url to acquire TLS cert"
help_userfile="path of user.yml defining profile for first admin"
help_subdomain="subdomain for this service (defaults to hostname)"

../base/runcmd

source /usr/local/include/argshelper
parseargs $@
requireargs userfile domain acme

if [[ -z "${subdomain}" ]]
then
  export subdomain=$(hostname)
fi

# ldap dc components from $domain
export suffix=$(sed -e 's/\./ /g' <<< ${domain} | xargs printf ",dc=%s" | sed -e 's/^,//')

# conf

mkdir -p /etc/ldap
mkdir -p /etc/sssd

sed -e "s/\${domain}/$domain/g" -e "s/\${hostname}/$subdomain/g" -e "s/\${suffix}/$suffix/g" conf/ldap.conf > /etc/ldap/ldap.conf
sed -e "s/\${domain}/$domain/g" -e "s/\${hostname}/$subdomain/g" -e "s/\${suffix}/$suffix/g" conf/sssd.conf > /etc/sssd/sssd.conf
cp conf/slapd /etc/default/slapd

sed -e "s/\${suffix}/$suffix/g" conf/org.ldif > /etc/ldap/org.ldif
sed -e "s/\${suffix}/$suffix/g" conf/access.ldif > /etc/ldap/access.ldif

cp include/* /usr/local/include/
cp scripts/* /usr/local/bin/

cat > /usr/local/include/ldap.env << EOF
   SUFFIX=${suffix}
   HOST=${subdomain}.${domain}
   DOMAIN=${domain}
EOF

# creds
if [[ ! -f /root/ldap_admin.passwd ]]
then
  admincred=$(generatecred)
  echo $admincred > /root/ldap_admin.passwd
  chmod 400 /root/ldap_admin.passwd
else
  admincred=$(cat /root/ldap_admin.passwd)
fi

if [[ ! -f /root/bootstrap.passwd ]]
then
  bootstrapcred=$(generatecred)
  echo $bootstrapcred > /root/bootstrap.passwd
  chmod 400 /root/bootstrap.passwd
else
  bootstrapcred=$(cat /root/bootstrap.passwd)
fi

if [[ ! -f /root/user.passwd ]]
then
  password=$(generatecred)
  echo $password > /root/user.passwd
  chmod 400 /root/user.passwd
else
  password=$(cat /root/user.passwd)
fi

# packages

debconf-set-selections <<EOF
  slapd slapd/internal/generated_adminpw password ${admincred}
  slapd slapd/password2 password ${admincred}
  slapd slapd/internal/adminpw password ${admincred}
  slapd slapd/password1 password ${admincred}
  slapd slapd/domain string ${domain}
  slapd shared/organization string homelab
EOF

apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes slapd sssd-ldap ldap-utils ldb-tools sssd-tools

wget --progress=dot:giga https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
chmod +x /usr/local/bin/yq

# setup
initcertbot --acme $acme --group openldap --san ${subdomain}.${domain} --chain /etc/ldap/ca.pem --key /etc/ldap/key.pem --cert /etc/ldap/cert.pem

ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f conf/certinfo.ldif
ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /etc/ldap/access.ldif

hostnamectl set-hostname ${subdomain}.${domain}

systemctl restart sssd.service
systemctl restart slapd


export LDAP_BIND_DN="cn=admin,${suffix}"
export LDAP_BIND_PW="${admincred}"

# default org units
ldapadd -H ldapi:/// -f /etc/ldap/org.ldif -x -D "$LDAP_BIND_DN" -w "$LDAP_BIND_PW"

# configure memberof module
ldapadd -H ldapi:/// -f conf/load_memberof.ldif -Q -Y EXTERNAL
ldapmodify -H ldapi:/// -f conf/load_refint.ldif -Q -Y EXTERNAL
ldapadd -H ldapi:/// -f conf/configure_refint.ldif -Q -Y EXTERNAL

# default groups
addldapgroup keycloak-realm-admin
addldapgroup step-admin
addldapgroup step-provisioner-admin
addldapgroup vault-user
addldapgroup vault-admin
addldapgroup ssh-ops
addldapgroup dns-ops
addldapgroup ldap-admin
addldapgroup k8s-core-admin
addldapgroup k8s-run-admin
addldapgroup minio-admin

# initial admin

username=$(yq .username $userfile)
givenname=$(yq .givenname $userfile)
surname=$(yq .surname $userfile)
email=$(yq .email $userfile)

addldapuser bootstrap Boot Strap bootstrap@${domain}
addldapuser $username $givenname $surname $email

# mail
# postmaster/abuse mailbox
addldapuser webmaster Web Master webmaster@${domain}
# sent to non-existent account
addldapuser catchall Catch All catchall@${domain}
# service account
addldapuser mailbot Mail Bot mailbot@${domain}

# first user is admin of all components
for admin in bootstrap $username
do
  addldapusertogroup $admin keycloak-realm-admin
  addldapusertogroup $admin step-admin
  addldapusertogroup $admin step-provisioner-admin
  addldapusertogroup $admin vault-user
  addldapusertogroup $admin vault-admin
  addldapusertogroup $admin ssh-ops
  addldapusertogroup $admin dns-ops
  addldapusertogroup $admin ldap-admin
  addldapusertogroup $admin k8s-core-admin
  addldapusertogroup $admin k8s-run-admin
  addldapusertogroup $admin minio-admin
done

ldappasswd  -x -D "$LDAP_BIND_DN" -w "$LDAP_BIND_PW" -s $bootstrapcred -S uid=bootstrap,ou=people,${suffix}
ldappasswd  -x -D "$LDAP_BIND_DN" -w "$LDAP_BIND_PW" -s $password -S uid=${username},ou=people,${suffix}

popd

echo success