#!/usr/bin/env bash
set -euo pipefail

if [[ ! -e /sbin/ldconfig.real ]]
then
  ln -s /sbin/ldconfig /sbin/ldconfig.real
fi

apt-get update
apt-get install -y gpg

curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
      | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
      | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
      | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

apt-get update
apt-get install -y nvidia-container-toolkit nvidia-container-runtime

cri="docker"
if command -v containerd
then
  cri="containerd"
fi

nvidia-ctk runtime configure --runtime=${cri} --set-as-default --cdi.enabled
nvidia-ctk config --set accept-nvidia-visible-devices-as-volume-mounts=true --in-place

if systemctl status ${cri}
then
  systemctl restart ${cri}
  systemctl is-active ${cri} --wait
fi

nvidia-smi # verify node can see gpu